### ISSUE TITLE
Support different pixel orders and RGBW strips

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_NeoPixel#1]
Right now the neopixel modules supports GRB order 400khz and 800khz pixel strips. We should update the module to support a wider range of pixel types:

RGB and other arbitrary byte orders
RGBW strips
This can probably all be done in the Python module as the low level pixel write function just takes an array of bytes to send out to the pixels (so it can change from 3-tuples to 4-tuples of color info for RGBW easily).

**Comment by mcauser** [comment]
https://github.com/micropython/micropython/issues/2478
and
https://github.com/micropython/micropython/pull/2536

**Comment by tannewt** [comment]
This is done. The constructor takes `bpp` which can be 4 for RGBW pixels.

**Comment by caternuson** [comment]
Reopening to address the pixel order part of the issue. How about this:
- Create a dictionary to map string based pixel order definitions to associated order tuple
- Add parameter to `__init__` to allow passing this in
- Set the ORDER tuple from the dictionary using the passed in parameter as key

Ex:
`pixels = neopixel.NeoPixel(board.NEOPIXEL, 1, pixel_order="RGB")`

**Comment by ladyada** [comment]
im cool w/this but rather than passing in "RGB" lets have a constant such as neopixel.RGB?

**Comment by caternuson** [comment]
Additionally, `bpp` could be set based on this argument. But probably shouldn't remove `bpp` from `__init__`? (would possibly break current examples)

I'm fine with constants. So this:
Ex:
`pixels = neopixel.NeoPixel(board.NEOPIXEL, 1, pixel_order=neopixel.RGB)`

**Comment by ladyada** [comment]
id leave `bpp` but prioritize if `order` is defined

**Comment by caternuson** [comment]
There's a rough draft PR. Comment on it over there. Will make lint happy and update doc examples if this seems like the right approach.

**Comment by ladyada** [comment]
i think we can just have the RGBW = (0, 1, 2, 3) rather than index?

**Comment by caternuson** [comment]
Good call, was over thinking it. Removed the dict.

**Comment by caternuson** [comment]
Closing back up. Different pixel order support added by: #24
