### ISSUE TITLE
Compute module 4 Error: RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)

### ISSUE THREAD

**Issue by Robokishan** [adafruit/Adafruit_CircuitPython_NeoPixel#102]
Hello I am trying to run example code on Compute Module 4. I have attached RGB led on pin D18 but having an error
RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)
Hardware	: BCM2711
Revision	        : b03140
Serial		: 100000002da55c1e
Model		: Raspberry Pi Compute Module 4 Rev 1.0

**Comment by ladyada** [comment]
hi you will have to ask https://github.com/jgarff/rpi_ws281x to add support for your board (we use their library)

**Comment by Robokishan** [comment]
I have already submitted pull request
