### ISSUE TITLE
Release assets not generated for 6.1.3

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/Adafruit_CircuitPython_NeoPixel#112]
Github actions didn't complete the 'upload-release-assets` action. Can this be re-run?

The Adafruit_CircuitPython_Bundle and the PyPI bundle appear to be correct.

**Comment by jposada202020** [comment]
I re-Run the works lets see if it works..

**Comment by jposada202020** [comment]
Assets are in https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/releases/tag/6.1.3
Thanks @lesamouraipourpre for pointing this out
