### ISSUE TITLE
7.0.0-alpha.2 gets NEOPIXEL_POWER in use on Qt Py

### ISSUE THREAD

**Issue by gmparis** [adafruit/Adafruit_CircuitPython_NeoPixel#113]
NeoPixel fails to intialize on Qt Py running 7.0.0-alpha.2. Example code below also fails with NEOPIXEL_POWER in use.
`import board
import digitalio
pin = digitalio.DigitalInOut(board.NEOPIXEL_POWER)`

**Comment by gmparis** [comment]
This was with 7.x-bundle from 05/27.

**Comment by tannewt** [comment]
Please comment if it's not fixed with an absolute newest build. The neopixel status pixel behavior was changed significantly since alpha 2. (We should release another alpha later this week once 6.3.0 is stable.)
