### ISSUE TITLE
Not working on fresh RPi4

### ISSUE THREAD

**Issue by SeiteBroken** [adafruit/Adafruit_CircuitPython_NeoPixel#117]
Hey i tried this tutorial (https://learn.adafruit.com/adafruit-neopixel-uberguide/python-circuitpython) on two fresh RPi4 and it doesn't work. Only some LEDs are showing some color, but not the one i want. I use a neopixel rgb ring with 12 LED's.

My wiring is this one: https://learn.adafruit.com/assets/63866

I also did this: https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi

Do you have any solution?

**Comment by TheKitty** [comment]
Please post your support questions on https://forums.adafruit.com/ with your code and pictures of your wiring along with which NeoPixel products you purchased as there are many LED strips in the market and not all of them conform to the data timing for NeoPixels.
