### ISSUE TITLE
Pi 400 Hardware Revision not supported

### ISSUE THREAD

**Issue by ganzgustav22** [adafruit/Adafruit_CircuitPython_NeoPixel#121]
I'm getting ws2811_init Hardware revision is not supported error messages on the Pi400. Is the Pi400 not yet added to the library?

I have googled for the error message and it seems you guys need to add every new Raspberry that comes out? Why? They're basically all the same, why not simply just check for "It's a Raspberry" instead of the particular model?

**Comment by ladyada** [comment]
please post the *exact* text error of the output

**Comment by ganzgustav22** [comment]
Sorry for the late reply. Happy new year :)

Here are the error messages:

> execMakroSteps fehler:   File "/usr/local/lib/python3.7/dist-packages/adafruit_circuitpython_pixelbuf-1.1.1-py3.7.egg/adafruit_pixelbuf.py", line 204, in show
    return self._transmit(self._post_brightness_buffer)
execMakroSteps fehler:   File "/usr/local/lib/python3.7/dist-packages/adafruit_circuitpython_neopixel-6.2.1-py3.7.egg/neopixel.py", line 167, in _transmit
    neopixel_write(self.pin, buffer)
execMakroSteps fehler:   File "/usr/local/lib/python3.7/dist-packages/Adafruit_Blinka-6.17.0-py3.7.egg/neopixel_write.py", line 35, in neopixel_write
    return _neopixel.neopixel_write(gpio, buf)
execMakroSteps fehler:   File "/usr/local/lib/python3.7/dist-packages/Adafruit_Blinka-6.17.0-py3.7.egg/adafruit_blinka/microcontroller/bcm283x/neopixel.py", line 80, in neopixel_write
    "ws2811_init failed with code {0} ({1})".format(resp, message)
execMakroSteps fehler: RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)

**Comment by ladyada** [comment]
oops thats an error in https://github.com/jgarff/rpi_ws281x which we use for the led
please open up the issue there :)
