### ISSUE TITLE
Example error consult

### ISSUE THREAD

**Issue by zkbutt** [adafruit/Adafruit_CircuitPython_NeoPixel#144]
![图片](https://user-images.githubusercontent.com/18031838/202998413-984ef7fc-0370-49ef-a662-e0d0be9e823f.png)

Traceback (most recent call last):
  File "....t001.py", line 4, in <module>
    pixels = neopixel.NeoPixel(board.NEOPIXEL, 1)
AttributeError: module 'board' has no attribute 'NEOPIXEL'

**Comment by zkbutt** [comment]
![图片](https://user-images.githubusercontent.com/18031838/203027974-ab3b3e24-b775-4848-bed5-09f0b0b19a9c.png)
How do we solve this? Can we disable this restriction

**Comment by Kasperror** [comment]
> ![图片](https://user-images.githubusercontent.com/18031838/203027974-ab3b3e24-b775-4848-bed5-09f0b0b19a9c.png) How do we solve this? Can we disable this restriction

If the board you're using is Raspberry Pi the solution sits in my PR #146 which authors did not approved yet.

**Comment by Kasperror** [comment]
> ![图片](https://user-images.githubusercontent.com/18031838/202998413-984ef7fc-0370-49ef-a662-e0d0be9e823f.png)
> 
> Traceback (most recent call last): File "....t001.py", line 4, in pixels = neopixel.NeoPixel(board.NEOPIXEL, 1) AttributeError: module 'board' has no attribute 'NEOPIXEL'

use hardware port instead, just like some examples show - `board.D18` or `board.D10` depending on the hadware you're using

**Comment by caternuson** [comment]
You can only use `board.NEOPIXEL` for boards that have a dedicated pin tied to a NeoPixel. General way to see what pins exist:
```python
import board
dir(board)
```

A Raspberry Pi does *not* have a NEOPIXEL pin.

For the permissions issue, see PR linked above.

Closing since not an actual library issue.
