### ISSUE TITLE
worth adding a clear function?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_NeoPixel#17]
Just a suggestion. Discuss...

This would just be a convenience function to make user syntax a little more obvious, since capability is currently there.
This:
```python
pixels.clear()
```
instead of (or in addition to) this:
```python
pixels.fill(0x000000)
```

**Comment by tannewt** [comment]
I would lean no because I don't like having two ways to do the same thing.

**Comment by dhalbert** [comment]
Any doc could use `pixels.fill(0)`, which is easier to read and remember.

**Comment by caternuson** [comment]
Good suggestion @dhalbert. Agree, much easier to read than the hex literal.

**Comment by caternuson** [comment]
Closing. Just use what @dhalbert suggested: `pixels.fill(0)`
