### ISSUE TITLE
Neopixel updates are slow

### ISSUE THREAD

**Issue by rhooper** [adafruit/Adafruit_CircuitPython_NeoPixel#27]
The neopixel library could benefit from a CircuitPython helper to offload computationally expensive setitem work to.  The use of brightness<1 is also slow.
See https://github.com/adafruit/circuitpython/issues/884

**Comment by rhooper** [comment]
I have done some experimental work on this, see adafruit/circuitpython#884

**Comment by gwertzman** [comment]
Yeah I noticed the same issue -- multiplying the brightness value through every value in the array on "show" is inefficient; much better to do the brightness calculation once when you set the value I think.

**Comment by rhooper** [comment]
This is now resolved with _pixelbuf in 5.0 beta and the latest neopixel.py that supports it.
