### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by webtop** [adafruit/Adafruit_CircuitPython_NeoPixel#44]
Testing a class I wrote which uses a NeoPixel strip attached to a RPi 2, running Python 3.5, when the scripts ends (normally) I get "swig/python detected a memory leak of type 'ws2811_t *', no destructor found.".

**Comment by ladyada** [comment]
yep - thats normal - the error is not in this library but in https://github.com/jgarff/rpi_ws281x
there's not much we can do about it, we only call their functions from within `blinka` - closin' this issue but you may want to reopen it there! :)
