### ISSUE TITLE
 'module' object has no attribute 'D18'

### ISSUE THREAD

**Issue by francescofact** [adafruit/Adafruit_CircuitPython_NeoPixel#55]
Hello, on my raspberry pi i get this error related to "board.D18".

The code line is:
pin = digitalio.DigitalInOut(board.D18)

The error is:
AttributeError: 'module' object has no attribute 'D18'

I have all the package installed and upgraded at the latest version.

**Comment by jerryneedell** [comment]
did you install "blinka" as in this guide ? https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi

also did you install a module called "board"  -- you should not have -- board is included in "adafruit_blinka"

**Comment by jerryneedell** [comment]
Also  -- takes look at this guide https://learn.adafruit.com/neopixels-on-raspberry-pi/overview

**Comment by francescofact** [comment]
thank you. 
i uninstalled board with pip3 (i don't know what package it is. it was already installed) and reinstalled "adafruit_blinka". now everything works. thank you

**Comment by paulesbats** [comment]
shhhtt
