### ISSUE TITLE
Brightness

### ISSUE THREAD

**Issue by Meresmata** [adafruit/Adafruit_CircuitPython_NeoPixel#6]
Hi to all,

 i just tried the new board Trinket M0 and Neopixels I get problems with the brightness() and brightness(float) method.

The Code is:
from board import *
import neopixel

NUMPIXELS = 8
 neopixels = neopixel.NeoPixel(D4, NUMPIXELS, brightness = 1, auto_write=False)
neopixels.fill(0xff0000)
neopixels.show()

When I call: 

neopixels.brightness(0.2)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  TypeError: 'int' object is not callable

>>> neopixels.brightness()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not callable

Do you know why?

**Comment by ladyada** [comment]
try neopixels.brightness = 0.2 ? :)
