### ISSUE TITLE
Neopixel_SPI RESET signal is too long

### ISSUE THREAD

**Issue by apalou21** [adafruit/Adafruit_CircuitPython_NeoPixel#61]
Hello dear maintainers,

I was curious and had a look at the Neopixel library code; I found that the initialization of the RESET on line 277 in the neopixel.py file set a 512 (6400000 * 80e-6) bytes long pattern, which is 8 times too much to get a 80us '0' line. This will slow down the refresh cycle for each Neopixel strip.

**Comment by caternuson** [comment]
@apalou21 Would you mind re-opening this issue here:
https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel_SPI/issues

We just refactored the NeoPixel SPI stuff into a separate library and repo.

**Comment by apalou21** [comment]
@caternuson no problem.
It's done.
I close this one.

**Comment by caternuson** [comment]
thanks!
