### ISSUE TITLE
 Outdated installation instructions

### ISSUE THREAD

**Issue by sixtyfive** [adafruit/Adafruit_CircuitPython_NeoPixel#89]
README.rst instructs:

> Please ensure all dependencies are available on the CircuitPython filesystem. This is easily achieved by downloading the Adafruit library and driver bundle.

From what I understand, it should instead be pointing towards a website similar to https://learn.adafruit.com/fancyled-library-for-circuitpython/install-software?

**Comment by dherrada** [comment]
Same as the last issue. That link essentially gives you the same instructions.
