### ISSUE TITLE
Running neopixel on Jetson Nano

### ISSUE THREAD

**Issue by i1212-blip** [adafruit/Adafruit_CircuitPython_NeoPixel#91]
Is there a way to run the library neopixel on jetson nano instead of running neopixel_spi? 
I'm facing a problem with jetson when using neopixel_spi. I'm trying to turn on  300 num pixels using an addressable led. When running the script; 168 led turns on instead of 300. I tried to increase the number of bytes(4096) but nothing changed. When running the script on Raspberry pi using neopixel library; it works perfectly. 

Below is the following script : 

"""
import time
import board
import neopixel_spi as neopixel

NUM_PIXELS = 300
PIXEL_ORDER = neopixeL.RGB
COLORS = (0xFF0000, 0x00FF00, 0x0000FF)
DELAY = 0.1

spi = board.SPI()

pixels = neopixel.NeoPixel_SPI(spi,
NUM_PIXELS,
pixel_order=PIXEL_ORDER,
auto_write=False)

while True:
for color in COLORS:
for i in range(NUM_PIXELS):
pixels[i] = color
pixels.show()
time.sleep(DELAY)
pixels.fill(0)

"""

**Comment by ladyada** [comment]
hi - please post to the NVIDIA support forum, they can assist you with hardware support for NeoPixel :)
